program: wandb_sweep.py
method: grid           # or bayes/random for smart search

metrics:
  goal: maximize
  name: Validation Accuracy

parameters:
  learning_rate:
    values: [0.1, 0.01]
  batch_size:
    values: [32, 64, 128]
  finetune:
    values: [true, false]